version: "3.1"
services:
  do-server:
    build: .
    ports:
        - "8066:80"
    volumes:
      - ./:/var/www
    links:
      - db
    networks:
      - default
  do-database:
    platform: linux/x86_64
    image: mysql/mysql-server:5.6
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
  do-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8067:80"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
volumes:
  persistent:
